### ISSUE TITLE
Portable Ops Plus support

### ISSUE THREAD

**Issue by knight-ki11er** [Kethen/-RemasteredControls_MGS_PPSSPP#1]
Is it possible?

**Comment by Kethen** [comment]
Possible, but you'll have to reverse the game enough to figure out what to do exactly. As the read me noted I did not do any reversing for this repo, only changed the hooking of https://github.com/TheOfficialFloW/RemasteredControls/tree/master/MetalGearSolid enough for it to work in PPSSPP and not just the vita. I have no good knowledge nor tools to carry out static and runtime PSP reversing.
